### ISSUE TITLE
Roadmap: The next few steps

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#88]
The next few big steps of the overall implementation should be
* [ ] Frontend: tests of the available code ontohub/ontohub-frontend#41, ontohub/ontohub-frontend#38, ontohub/ontohub-frontend#39
* [ ] Frontend: Check backend version ontohub/ontohub-frontend#36
* [ ] Backend: basic git API #9
* [ ] Frontend: basic git GUI ontohub/ontohub-frontend#57
* [ ] System-tests: all reasonable system tests ontohub/system-test#1
---
* [ ] Backend: user registration (with captcha) and deletion API https://github.com/ontohub/ontohub-backend/issues/86
* [ ] Frontend: user registration and deletion GUI https://github.com/ontohub/ontohub-frontend/issues/58
* [ ] Backend: authorisation https://github.com/ontohub/ontohub-backend/issues/87
* [ ] Frontend: authorisation https://github.com/ontohub/ontohub-frontend/issues/59
---
* [ ] Hets: basic OMS analysis (e.g. only the name) https://github.com/spechub/Hets/issues/1690
* [ ] hets-rabbitmq-wrapper: Call Hets for OMS analysis https://github.com/ontohub/hets-rabbitmq-wrapper/issues/12

These blocks contain tasks that can be done more or less in parallel. The
